#!/bin/bash

echo "Usage: ./sudoku  size inputfile"
echo "make all"
make all
echo " ---------------------------------------------------------------------------------------------------------------------- "
echo "| For n = 16 and n = 25 they take some time to show the output since my algorithm for solving the sudoku is bruteforce.|"
echo " ---------------------------------------------------------------------------------------------------------------------- "

echo "Running the example of sudoku with n = 4"
./solver 4 ./input4.txt


echo "Running the example of sudoku with n = 9"
./solver 9 ./input9.txt

echo "Running the example of sudoku with n = 16"
./solver 16 ./input16.txt


echo "Running the example of sudoku with n = 25"
./solver 25 ./input25.txt
